name: CD
on:
  # Runs on all push events on main.
  push:
    branches: [ main ]

permissions:
  # Can only read the source code.
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/lint

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/test

  build:
    name: Build
    needs: test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build

  semver:
    name: Semver
    needs: build
    runs-on: ubuntu-18.04
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/actions/semver
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
